### ISSUE TITLE
Error: Cannot find module 'p-queue'

### ISSUE THREAD

**Issue by salemkode** [Permissionless-Software-Foundation/psf-slp-indexer#48]
I'm trying to install indexer in my server but it generates this streak at the beginning of the installation

```
Error: Cannot find module 'p-queue'
Require stack:
- /home/salemkode/dev/psf-slp-indexer/src/adapters/slp-indexer/lib/retry-queue.js
- /home/salemkode/dev/psf-slp-indexer/src/adapters/slp-indexer/lib/transaction.js
- /home/salemkode/dev/psf-slp-indexer/src/adapters/slp-indexer/lib/cache.js
- /home/salemkode/dev/psf-slp-indexer/src/adapters/slp-indexer/index.js
- /home/salemkode/dev/psf-slp-indexer/src/adapters/index.js
- /home/salemkode/dev/psf-slp-indexer/src/controllers/index.js
- /home/salemkode/dev/psf-slp-indexer/bin/server.js
- /home/salemkode/dev/psf-slp-indexer/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/salemkode/dev/psf-slp-indexer/src/adapters/slp-indexer/lib/retry-queue.js:12:16)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/salemkode/dev/psf-slp-indexer/src/adapters/slp-indexer/lib/transaction.js:16:20)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/salemkode/dev/psf-slp-indexer/src/adapters/slp-indexer/lib/retry-queue.js',
    '/home/salemkode/dev/psf-slp-indexer/src/adapters/slp-indexer/lib/transaction.js',
    '/home/salemkode/dev/psf-slp-indexer/src/adapters/slp-indexer/lib/cache.js',
    '/home/salemkode/dev/psf-slp-indexer/src/adapters/slp-indexer/index.js',
    '/home/salemkode/dev/psf-slp-indexer/src/adapters/index.js',
    '/home/salemkode/dev/psf-slp-indexer/src/controllers/index.js',
    '/home/salemkode/dev/psf-slp-indexer/bin/server.js',
    '/home/salemkode/dev/psf-slp-indexer/index.js'
  ]
}
```

**Comment by salemkode** [comment]
I am using `yarn`

When I use npm no error show
